package com.example.myFitHololenzApp

import android.app.Activity.RESULT_OK
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.util.Log
import android.widget.Toast
import androidx.core.app.ActivityCompat
import androidx.core.app.NotificationCompat
import androidx.core.content.ContentProviderCompat.requireContext
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.fitness.Fitness
import com.google.android.gms.fitness.FitnessOptions
import com.google.android.gms.fitness.data.DataPoint
import com.google.android.gms.fitness.data.DataSet
import com.google.android.gms.fitness.data.DataSource
import com.google.android.gms.fitness.data.DataType
import com.google.android.gms.fitness.request.DataReadRequest
import com.google.android.gms.fitness.request.DataSourcesRequest
import com.google.android.gms.fitness.request.OnDataPointListener
import com.google.android.gms.fitness.request.SensorRequest
import com.google.android.gms.fitness.result.DataReadResponse
import com.google.android.gms.tasks.Tasks
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.util.concurrent.TimeUnit

class Dataworker(context: Context, workerParams: WorkerParameters) : Worker(context, workerParams)  {

    private val context1 = context
    private val fitnessOptions = FitnessOptions.builder().addDataType(DataType.TYPE_HEART_RATE_BPM).build()
    var GOOGLE_FIT_PERMISSIONS_REQUEST_CODE = 123456
    val REQUEST_CODE = 1
    private val TAG = "thread"


    //val acc = GoogleSignIn.requestPermissions(context1,GOOGLE_FIT_PERMISSIONS_REQUEST_CODE,GoogleSignIn.getAccountForExtension(context1, fitnessOptions),fitnessOptions)
    private var dataPointListener: OnDataPointListener? = null
    private val runningQOrLater =
        android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q
    enum class FitActionRequestCode {
        FIND_DATA_SOURCES
    }

    override fun doWork(): Result {
        val fitnessOptions = FitnessOptions.builder().addDataType(DataType.TYPE_HEART_RATE_BPM).build()

//        val fitnessOptions = FitnessOptions.builder()
//            .addDataType(DataType.TYPE_STEP_COUNT_DELTA, FitnessOptions.ACCESS_READ)
//            .addDataType(DataType.AGGREGATE_STEP_COUNT_DELTA, FitnessOptions.ACCESS_READ)
//            .build()

        //checkPermissionsAndRun(FitActionRequestCode.FIND_DATA_SOURCES)
        //accessGoogleFit()
        test()


        createNotification("Background Task", "This notification is generated by workManager")
        return Result.success()
    }
//    private fun checkPermissionsAndRun(fitActionRequestCode: FitActionRequestCode) {
//        if (permissionApproved()) {
//            fitSignIn(fitActionRequestCode)
//        } else {
//            //requestRuntimePermissions(fitActionRequestCode)
//            Log.e(TAG, "did get permission")
//        }
//    }
//    private fun permissionApproved(): Boolean {
//        val approved = if (runningQOrLater) {
//            PackageManager.PERMISSION_GRANTED == ActivityCompat.checkSelfPermission(
//                context1,Manifest.permission.TYPE_HEART_RATE_BPM)
//        } else {
//            true
//        }
//        return approved
//    }

    /**
     * Checks that the user is signed in, and if so, executes the specified function. If the user is
     * not signed in, initiates the sign in flow, specifying the post-sign in function to execute.
     *
     * @param requestCode The request code corresponding to the action to perform after sign in.
     */
//    private fun fitSignIn(requestCode: FitActionRequestCode) {
//        if (oAuthPermissionsApproved()) {
//            performActionForRequestCode(requestCode)
//        } else {
//            requestCode.let {
//            GoogleSignIn.requestPermissions(
//                context1, // your activity
//                GOOGLE_FIT_PERMISSIONS_REQUEST_CODE, // e.g. 1
//                getGoogleAccount(),
//                fitnessOptions)
//            }
//        }
//    }

    private fun oAuthPermissionsApproved() = GoogleSignIn.hasPermissions(getGoogleAccount(), fitnessOptions)

    /**
     * Gets a Google account for use in creating the Fitness client. This is achieved by either
     * using the last signed-in account, or if necessary, prompting the user to sign in.
     * `getAccountForExtension` is recommended over `getLastSignedInAccount` as the latter can
     * return `null` if there has been no sign in before.
     */
    private fun getGoogleAccount() = GoogleSignIn.getAccountForExtension(context1, fitnessOptions)

    /**
     * Handles the callback from the OAuth sign in flow, executing the post sign in function
     */


    /**
     * Runs the desired method, based on the specified request code. The request code is typically
     * passed to the Fit sign-in flow, and returned with the success callback. This allows the
     * caller to specify which method, post-sign-in, should be called.
     *
     * @param requestCode The code corresponding to the action to perform.
     */
    private fun performActionForRequestCode(requestCode: FitActionRequestCode) = when (requestCode) {
        FitActionRequestCode.FIND_DATA_SOURCES -> accessGoogleFit()
    }

    private fun oAuthErrorMsg(requestCode: Int, resultCode: Int) {
        val message = """
            There was an error signing into Fit. Check the troubleshooting section of the README
            for potential issues.
            Request code was: $requestCode
            Result code was: $resultCode
        """.trimIndent()
        Log.e(TAG, message)
    }


    private fun accessGoogleFit() {
        Log.v(TAG,"testtstts");


        Fitness.getRecordingClient(context1, GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
            // This example shows subscribing to a DataType, across all possible data
            // sources. Alternatively, a specific DataSource can be used.
            .subscribe(DataType.TYPE_HEART_RATE_BPM)
            .addOnSuccessListener {
                Log.i(TAG, "Successfully subscribed!")
            }
            .addOnFailureListener { e ->
                Log.w(TAG, "There was a problem subscribing.", e)
            }


        Fitness.getRecordingClient(context1, GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
            .listSubscriptions()
            .addOnSuccessListener { subscriptions ->
                for (sc in subscriptions) {
                    val dt = sc.dataType
                    if (dt != null) {
                        Log.i(TAG, "Active subscription for data type: ${dt.name}")
                    }
                }
            }

        Fitness.getSensorsClient(context1, GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
            .findDataSources(
                DataSourcesRequest.Builder()
                    .setDataTypes(DataType.TYPE_HEART_RATE_BPM)
                    .setDataSourceTypes(DataSource.TYPE_RAW)
                    .build())
            .addOnSuccessListener { dataSources ->
                Log.i(TAG, "Data source found: $dataSources")
                for (dataSource in dataSources) {
                    Log.i(TAG, "Data source found: $dataSource")
                    Log.i(TAG, "Data Source type: " + dataSource.dataType.name)
                    // Let's register a listener to receive Activity data!
                    if (dataSource.dataType == DataType.TYPE_HEART_RATE_BPM && dataPointListener == null) {
                        Log.i(TAG, "Data source for LOCATION_SAMPLE found!  Registering.")
                        registerFitnessDataListener(dataSource, DataType.TYPE_HEART_RATE_BPM,fitnessOptions)
                    }
                }
            }
 //               Log.v(TAG,dataSources.toString());
//                dataSources.forEach {
//                    Log.v(TAG,it.toString());
//
//                    if (it.dataType == DataType.TYPE_HEART_RATE_BPM) {
//                        Log.i(TAG, "Data source for STEP_COUNT_DELTA found!")
//
//
//                    }
//                }
//            }
            .addOnFailureListener { e ->
                Log.e(TAG, "Find data sources request failed", e)
            }

 //       val account = GoogleSignIn.getAccountForExtension(context1, fitnessOptions)
//        val response = Fitness.getHistoryClient(context1, account)
//            .readData(readRequest)
//            .addOnSuccessListener({ response ->
//                // Use response data here
//                Log.i(ContentValues.TAG, "OnSuccess()")
//            })
//            .addOnFailureListener({ e -> Log.d(ContentValues.TAG, "OnFailure()", e) })
//        val readDataResponse = Tasks.await<DataReadResponse>(response)
//        val dataSet = readDataResponse.getDataSet(DataType.TYPE_STEP_COUNT_DELTA)
//        print("hii")
//        Log.v(TAG,dataSet.toString());

        //FirstFragment.phoneData =






    }


    fun registerFitnessDataListener(dataSource: DataSource, dataType: DataType,fitnessOptions:FitnessOptions) {
        // [START register_data_listener]
        dataPointListener = OnDataPointListener { dataPoint ->
            for (field in dataPoint.dataType.fields) {
                val value = dataPoint.getValue(field)
                Log.i(TAG, "Detected DataPoint field: ${field.name}")
                Log.i(TAG, "Detected DataPoint value: $value")
            }
        }
        Fitness.getSensorsClient(context1,  GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
            .add(
                SensorRequest.Builder()
                    .setDataSource(dataSource) // Optional but recommended for custom data sets.
                    .setDataType(dataType) // Can't be omitted.
                    .setSamplingRate(10, TimeUnit.SECONDS)
                    .build(),
                dataPointListener!!
            )
            .addOnCompleteListener { task ->
                if (task.isSuccessful) {
                    Log.i(TAG, "Listener registered!")
                } else {
                    Log.e(TAG, "Listener not registered.", task.exception)
                }
            }
        // [END register_data_listener]
    }


//    fun getListener(fitnessOptions:FitnessOptions){
//        val listener = OnDataPointListener { dataPoint ->
//            for (field in dataPoint.dataType.fields) {
//                val value = dataPoint.getValue(field)
//                Log.i(TAG, "Detected DataPoint field: ${field.name}")
//                Log.i(TAG, "Detected DataPoint value: $value")
//            }
//        }
//
//        Fitness.getSensorsClient(context1, GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
//            .add(
//                SensorRequest.Builder()
//                    .setDataSource(dataSource) // Optional but recommended for custom
//                    // data sets.
//                    .setDataType(dataType) // Can't be omitted.
//                    .setSamplingRate(10, TimeUnit.SECONDS)
//                    .build(),
//                listener
//            )
//            .addOnSuccessListener {
//                Log.i(TAG, "Listener registered!")
//            }
//            .addOnFailureListener {
//                Log.e(TAG, "Listener not registered.", task.exception)
//            }
//    }

    fun createNotification(title: String, description: String) {

        var notificationManager =
            applicationContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val notificationChannel =
                NotificationChannel("101", "channel", NotificationManager.IMPORTANCE_DEFAULT)
            notificationManager.createNotificationChannel(notificationChannel)
        }

        val notificationBuilder = NotificationCompat.Builder(applicationContext, "101")
            .setContentTitle(title)
            .setContentText(description)
            .setSmallIcon(R.drawable.ic_launcher_background)

        notificationManager.notify(1, notificationBuilder.build())

    }


    fun test(){
        val endTime = LocalDateTime.now().atZone(ZoneId.systemDefault())
        val startTime = endTime.minusWeeks(1)
        Log.i(TAG, "Range Start: $startTime")
        Log.i(TAG, "Range End: $endTime")

        val readRequest =
            DataReadRequest.Builder()
                // The data request can specify multiple data types to return,
                // effectively combining multiple data queries into one call.
                // This example demonstrates aggregating only one data type.
                .aggregate(DataType.TYPE_HEART_RATE_BPM)
                // Analogous to a "Group By" in SQL, defines how data should be
                // aggregated.
                // bucketByTime allows for a time span, whereas bucketBySession allows
                // bucketing by <a href="/fit/android/using-sessions">sessions</a>.
                .bucketByTime(1, TimeUnit.DAYS)
                .setTimeRange(startTime.toEpochSecond(), endTime.toEpochSecond(), TimeUnit.SECONDS)
                .build()

        Fitness.getHistoryClient(context1, GoogleSignIn.getAccountForExtension(context1, fitnessOptions))
            .readData(readRequest)
            .addOnSuccessListener { response ->
                // The aggregate query puts datasets into buckets, so flatten into a
                // single list of datasets
                for (dataSet in response.buckets.flatMap { it.dataSets }) {
                    dumpDataSet(dataSet)
                }
            }
            .addOnFailureListener { e ->
                Log.w(TAG,"There was an error reading data from Google Fit", e)
            }


    }
    fun dumpDataSet(dataSet: DataSet) {
        Log.i(TAG, "Data returned for Data type: ${dataSet.dataType.name}")
        for (dp in dataSet.dataPoints) {
            Log.i(TAG,"Data point:")
            Log.i(TAG,"\tType: ${dp.dataType.name}")
            Log.i(TAG,"\tStart: ${dp.getStartTimeString()}")
            Log.i(TAG,"\tEnd: ${dp.getEndTimeString()}")
            for (field in dp.dataType.fields) {
                Log.i(TAG,"\tField: ${field.name.toString()} Value: ${dp.getValue(field)}")
            }
        }
    }

    fun DataPoint.getStartTimeString() = Instant.ofEpochSecond(this.getStartTime(TimeUnit.SECONDS))
        .atZone(ZoneId.systemDefault())
        .toLocalDateTime().toString()

    fun DataPoint.getEndTimeString() = Instant.ofEpochSecond(this.getEndTime(TimeUnit.SECONDS))
        .atZone(ZoneId.systemDefault())
        .toLocalDateTime().toString()


}